### PR TITLE
Isuruf patch 1

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
needs more work

**Comment by isuruf** [comment]
needs more work

**Comment by isuruf** [comment]
needs more work

**Comment by isuruf** [comment]
+1 to merge

**Comment by isuruf** [comment]
@asmeurer, all the labels here were added automatically.

**Comment by isuruf** [comment]
cc @certik, @moorepants, since you were interested in adding labels by those who don't have push access

**Comment by moorepants** [comment]
This looks pretty cool. I assume it is dependent on specific phrases in the comments?

**Comment by isuruf** [comment]
Yes, See https://github.com/isuruf/sympy-pr-webapp/blob/master/webapp.py#L62-L63

**Comment by asmeurer** [comment]
My idea was to just use the labels (no comments). That way we don't have to rely on specific text in comments (which has false positives), and it reduces the notification noise. 

Basically, when someone adds "Needs better patch" or "Needs review", the system immediately removes it, and sets the status. Or if it's possible, could it remove it only when a new commit is pushed (then we almost wouldn't even need the status)?

We could also, instead of a label, use the 👍 and 👎 on the OP of the PR to auto-set a status (the downside there is that people might interpret those emoji differently than as a review for the PR).

**Comment by isuruf** [comment]
It's possible to remove a label when a new commit is added. See above when 1fbe59c was added, the label was changed to SymPy's turn

**Comment by asmeurer** [comment]
So maybe we don't rely need the comment or status stuff. All we really need is for the labels to be reset on new commits. The status stuff would be nice though, since I generally look at that when I'm looking through the list of PRs.

**Comment by isuruf** [comment]
Github doesn't give you events on adding reactions like  :+1:. https://developer.github.com/webhooks/#events. Apart from that, Github sends almost all of the events generated, so we can customize it to whatever we like. 
If you can give details on the workflow you have in mind in point form, we can discuss it and I can implement it.
One thing about adding labels is that a reviewer who doesn't have push access cannot set it.

**Comment by asmeurer** [comment]
I didn't consider reviewers without push access. Realistically, anyone who is doing heavy reviewing should be given push access.

**Comment by isuruf** [comment]
Okay.
There are 2 options.
1. Labels only - a reviewer would add `needs work` label and then when a commit is pushed that label is removed
2. Status - a reviewer would add `needs work` label and then a failure status is added to the last commit. Also `needs work` is also removed. When a commit is pushed, failure status is removed.

**Comment by asmeurer** [comment]
The original reason I had thought of the second way was that it allows multiple reviewers to set the status.

**Comment by isuruf** [comment]
Can you explain the last comment a bit?

**Comment by asmeurer** [comment]
If we use a label system, the only way for multiple people to mark a PR with a label is if the bot removes the label after each person adds it.

**Comment by isuruf** [comment]
With the label system, only one reviewer needs to mark a PR with a label. Why would several reviewers mark it?

**Comment by asmeurer** [comment]
That's how the "sign off" feature works on BitBucket. I guess it's not a required feature. Actually, since we only require one review, it's not a necessary feature.

**Pull request closed without merging**
